//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anticipack.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anticipack.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity created successfully.
        /// </summary>
        public static string ActivityCreated {
            get {
                return ResourceManager.GetString("ActivityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity deleted successfully.
        /// </summary>
        public static string ActivityDeleted {
            get {
                return ResourceManager.GetString("ActivityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Category_Accessories {
            get {
                return ResourceManager.GetString("Category_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Category_Clothing {
            get {
                return ResourceManager.GetString("Category_Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Category_Documents {
            get {
                return ResourceManager.GetString("Category_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string Category_Electronics {
            get {
                return ResourceManager.GetString("Category_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Category_Entertainment {
            get {
                return ResourceManager.GetString("Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Category_Food {
            get {
                return ResourceManager.GetString("Category_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Category_Health {
            get {
                return ResourceManager.GetString("Category_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Category_Miscellaneous {
            get {
                return ResourceManager.GetString("Category_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        public static string Category_Outdoor {
            get {
                return ResourceManager.GetString("Category_Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string Category_Shoes {
            get {
                return ResourceManager.GetString("Category_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toiletries.
        /// </summary>
        public static string Category_Toiletries {
            get {
                return ResourceManager.GetString("Category_Toiletries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Packing Activity.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        public static string DeleteActivityMessage {
            get {
                return ResourceManager.GetString("DeleteActivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity?.
        /// </summary>
        public static string DeleteActivityTitle {
            get {
                return ResourceManager.GetString("DeleteActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create activity.
        /// </summary>
        public static string FailedToCreate {
            get {
                return ResourceManager.GetString("FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete activity.
        /// </summary>
        public static string FailedToDelete {
            get {
                return ResourceManager.GetString("FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load activities.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last packed:.
        /// </summary>
        public static string LastPacked {
            get {
                return ResourceManager.GetString("LastPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading activities....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Packing Activity.
        /// </summary>
        public static string NewPackingActivity {
            get {
                return ResourceManager.GetString("NewPackingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Packing Activities.
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first packing activity to get started..
        /// </summary>
        public static string NoActivitiesDescription {
            get {
                return ResourceManager.GetString("NoActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Now.
        /// </summary>
        public static string PackNow {
            get {
                return ResourceManager.GetString("PackNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search activities....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
    }
}
