//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anticipack.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anticipack.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been archived.
        /// </summary>
        public static string ActivityArchived {
            get {
                return ResourceManager.GetString("ActivityArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity created successfully.
        /// </summary>
        public static string ActivityCreated {
            get {
                return ResourceManager.GetString("ActivityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity deleted successfully.
        /// </summary>
        public static string ActivityDeleted {
            get {
                return ResourceManager.GetString("ActivityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity ID is empty.
        /// </summary>
        public static string ActivityIdEmpty {
            get {
                return ResourceManager.GetString("ActivityIdEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Management.
        /// </summary>
        public static string ActivityManagement {
            get {
                return ResourceManager.GetString("ActivityManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity with ID &apos;{0}&apos; not found.
        /// </summary>
        public static string ActivityNotFound {
            get {
                return ResourceManager.GetString("ActivityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Type.
        /// </summary>
        public static string ActivityType {
            get {
                return ResourceManager.GetString("ActivityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; has been unarchived.
        /// </summary>
        public static string ActivityUnarchived {
            get {
                return ResourceManager.GetString("ActivityUnarchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your first item.
        /// </summary>
        public static string AddFirstItem {
            get {
                return ResourceManager.GetString("AddFirstItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Items.
        /// </summary>
        public static string AddItems {
            get {
                return ResourceManager.GetString("AddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} Items.
        /// </summary>
        public static string AddItemsCount {
            get {
                return ResourceManager.GetString("AddItemsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add notes about this item....
        /// </summary>
        public static string AddNotesAboutItem {
            get {
                return ResourceManager.GetString("AddNotesAboutItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string AI {
            get {
                return ResourceManager.GetString("AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your trip.
        /// </summary>
        public static string AiDescribeTrip {
            get {
                return ResourceManager.GetString("AiDescribeTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI error: {0}.
        /// </summary>
        public static string AiError {
            get {
                return ResourceManager.GetString("AiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Generate to get AI-powered packing suggestions.
        /// </summary>
        public static string AiHint {
            get {
                return ResourceManager.GetString("AiHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI service is not configured. Please set the API key..
        /// </summary>
        public static string AiNotConfigured {
            get {
                return ResourceManager.GetString("AiNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 2-week beach vacation, business trip to NYC....
        /// </summary>
        public static string AiPromptPlaceholder {
            get {
                return ResourceManager.GetString("AiPromptPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string AiSuggestions {
            get {
                return ResourceManager.GetString("AiSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple Pay.
        /// </summary>
        public static string ApplePay {
            get {
                return ResourceManager.GetString("ApplePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to capture audio. Please check your microphone..
        /// </summary>
        public static string AudioCaptureError {
            get {
                return ResourceManager.GetString("AudioCaptureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive activities not packed for this many days (0 = disabled).
        /// </summary>
        public static string AutoArchiveDaysHint {
            get {
                return ResourceManager.GetString("AutoArchiveDaysHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Archive Inactive Activities.
        /// </summary>
        public static string AutoArchiveDaysLabel {
            get {
                return ResourceManager.GetString("AutoArchiveDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AutoArchiveDisabled {
            get {
                return ResourceManager.GetString("AutoArchiveDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your message! Our support team will get back to you as soon as possible..
        /// </summary>
        public static string AutoReplyMessage {
            get {
                return ResourceManager.GetString("AutoReplyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoTheme {
            get {
                return ResourceManager.GetString("AutoTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic theme based on system preferences.
        /// </summary>
        public static string AutoThemeTitle {
            get {
                return ResourceManager.GetString("AutoThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Time.
        /// </summary>
        public static string AvgTime {
            get {
                return ResourceManager.GetString("AvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separate items by new line or comma. All items will be added to the selected category..
        /// </summary>
        public static string BulkAddHint {
            get {
                return ResourceManager.GetString("BulkAddHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toothbrush, Toothpaste
        ///Shampoo
        ///Soap, Towel.
        /// </summary>
        public static string BulkAddPlaceholder {
            get {
                return ResourceManager.GetString("BulkAddPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Category_Accessories {
            get {
                return ResourceManager.GetString("Category_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Category_Clothing {
            get {
                return ResourceManager.GetString("Category_Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Category_Documents {
            get {
                return ResourceManager.GetString("Category_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string Category_Electronics {
            get {
                return ResourceManager.GetString("Category_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Category_Entertainment {
            get {
                return ResourceManager.GetString("Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Category_Food {
            get {
                return ResourceManager.GetString("Category_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Category_Health {
            get {
                return ResourceManager.GetString("Category_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Category_Miscellaneous {
            get {
                return ResourceManager.GetString("Category_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        public static string Category_Outdoor {
            get {
                return ResourceManager.GetString("Category_Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string Category_Shoes {
            get {
                return ResourceManager.GetString("Category_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toiletries.
        /// </summary>
        public static string Category_Toiletries {
            get {
                return ResourceManager.GetString("Category_Toiletries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Archive Status.
        /// </summary>
        public static string ChangeArchiveStatus {
            get {
                return ResourceManager.GetString("ChangeArchiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared to Last Time.
        /// </summary>
        public static string ComparedToLastTime {
            get {
                return ResourceManager.GetString("ComparedToLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to archive &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmArchive {
            get {
                return ResourceManager.GetString("ConfirmArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have packed {0} out of {1} items. The remaining {2} item(s) will be automatically checked. Do you want to finish packing?.
        /// </summary>
        public static string ConfirmFinishPackingWithAutoCheck {
            get {
                return ResourceManager.GetString("ConfirmFinishPackingWithAutoCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark all items as unpacked?.
        /// </summary>
        public static string ConfirmResetAllItems {
            get {
                return ResourceManager.GetString("ConfirmResetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to unarchive &quot;{0}&quot;?.
        /// </summary>
        public static string ConfirmUnarchive {
            get {
                return ResourceManager.GetString("ConfirmUnarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string CopyTitle {
            get {
                return ResourceManager.GetString("CopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Packing Activity.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating....
        /// </summary>
        public static string Creating {
            get {
                return ResourceManager.GetString("Creating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or enter a custom amount.
        /// </summary>
        public static string CustomAmount {
            get {
                return ResourceManager.GetString("CustomAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your experience.
        /// </summary>
        public static string CustomizeExperience {
            get {
                return ResourceManager.GetString("CustomizeExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string DarkThemeTitle {
            get {
                return ResourceManager.GetString("DarkThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data &amp; Storage.
        /// </summary>
        public static string DataStorage {
            get {
                return ResourceManager.GetString("DataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        public static string Decrease {
            get {
                return ResourceManager.GetString("Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity.
        /// </summary>
        public static string DeleteActivity {
            get {
                return ResourceManager.GetString("DeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this packing activity?
        ///This action cannot be undone..
        /// </summary>
        public static string DeleteActivityConfirm {
            get {
                return ResourceManager.GetString("DeleteActivityConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        public static string DeleteActivityMessage {
            get {
                return ResourceManager.GetString("DeleteActivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity?.
        /// </summary>
        public static string DeleteActivityTitle {
            get {
                return ResourceManager.GetString("DeleteActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;?.
        /// </summary>
        public static string DeleteItemMessage {
            get {
                return ResourceManager.GetString("DeleteItemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        public static string DeleteItemTitle {
            get {
                return ResourceManager.GetString("DeleteItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect All.
        /// </summary>
        public static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your support helps us continue developing and improving Anticipack. Thank you for considering a donation!.
        /// </summary>
        public static string DonateDescription {
            get {
                return ResourceManager.GetString("DonateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment could not be completed. Please try again..
        /// </summary>
        public static string DonateFailed {
            get {
                return ResourceManager.GetString("DonateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string DonateNow {
            get {
                return ResourceManager.GetString("DonateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anticipack Donation.
        /// </summary>
        public static string DonatePurpose {
            get {
                return ResourceManager.GetString("DonatePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your generous donation!.
        /// </summary>
        public static string DonateSuccess {
            get {
                return ResourceManager.GetString("DonateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every contribution, big or small, makes a difference. Thank you for your support!.
        /// </summary>
        public static string DonateThankYou {
            get {
                return ResourceManager.GetString("DonateThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Anticipack.
        /// </summary>
        public static string DonateTitle {
            get {
                return ResourceManager.GetString("DonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} duplicate(s) removed.
        /// </summary>
        public static string DuplicatesRemoved {
            get {
                return ResourceManager.GetString("DuplicatesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} existing item(s) skipped.
        /// </summary>
        public static string DuplicatesSkipped {
            get {
                return ResourceManager.GetString("DuplicatesSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string DurationMinutes {
            get {
                return ResourceManager.GetString("DurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity.
        /// </summary>
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter activity name....
        /// </summary>
        public static string EnterActivityName {
            get {
                return ResourceManager.GetString("EnterActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Items.
        /// </summary>
        public static string EnterItems {
            get {
                return ResourceManager.GetString("EnterItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding item: {0}.
        /// </summary>
        public static string ErrorAddingItem {
            get {
                return ResourceManager.GetString("ErrorAddingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error finishing packing: {0}.
        /// </summary>
        public static string ErrorFinishingPacking {
            get {
                return ResourceManager.GetString("ErrorFinishingPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting items: {0}.
        /// </summary>
        public static string ErrorResettingItems {
            get {
                return ResourceManager.GetString("ErrorResettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving completion: {0}.
        /// </summary>
        public static string ErrorSavingCompletion {
            get {
                return ResourceManager.GetString("ErrorSavingCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving item state: {0}.
        /// </summary>
        public static string ErrorSavingItemState {
            get {
                return ResourceManager.GetString("ErrorSavingItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy packing activity: {0}.
        /// </summary>
        public static string FailedToCopyActivity {
            get {
                return ResourceManager.GetString("FailedToCopyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create activity.
        /// </summary>
        public static string FailedToCreate {
            get {
                return ResourceManager.GetString("FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete activity.
        /// </summary>
        public static string FailedToDelete {
            get {
                return ResourceManager.GetString("FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete packing activity: {0}.
        /// </summary>
        public static string FailedToDeleteActivity {
            get {
                return ResourceManager.GetString("FailedToDeleteActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete item: {0}.
        /// </summary>
        public static string FailedToDeleteItem {
            get {
                return ResourceManager.GetString("FailedToDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load activities.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load items.
        /// </summary>
        public static string FailedToLoadItems {
            get {
                return ResourceManager.GetString("FailedToLoadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save item order: {0}.
        /// </summary>
        public static string FailedToSaveItemOrder {
            get {
                return ResourceManager.GetString("FailedToSaveItemOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update archive status.
        /// </summary>
        public static string FailedToUpdateArchiveStatus {
            get {
                return ResourceManager.GetString("FailedToUpdateArchiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update item: {0}.
        /// </summary>
        public static string FailedToUpdateItem {
            get {
                return ResourceManager.GetString("FailedToUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Now.
        /// </summary>
        public static string FinishNow {
            get {
                return ResourceManager.GetString("FinishNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Packing.
        /// </summary>
        public static string FinishPacking {
            get {
                return ResourceManager.GetString("FinishPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free up storage space.
        /// </summary>
        public static string FreeUpStorage {
            get {
                return ResourceManager.GetString("FreeUpStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All items packed.
        /// </summary>
        public static string FullyPacked {
            get {
                return ResourceManager.GetString("FullyPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating....
        /// </summary>
        public static string Generating {
            get {
                return ResourceManager.GetString("Generating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Pay.
        /// </summary>
        public static string GooglePay {
            get {
                return ResourceManager.GetString("GooglePay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great!.
        /// </summary>
        public static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Checked Items.
        /// </summary>
        public static string HideCheckedItems {
            get {
                return ResourceManager.GetString("HideCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        public static string Increase {
            get {
                return ResourceManager.GetString("Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item already exists in your list.
        /// </summary>
        public static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item name....
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} items packed.
        /// </summary>
        public static string ItemsPacked {
            get {
                return ResourceManager.GetString("ItemsPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition is not supported for the selected language. Falling back to English..
        /// </summary>
        public static string LanguageNotSupported {
            get {
                return ResourceManager.GetString("LanguageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Packed.
        /// </summary>
        public static string LastPackedLabel {
            get {
                return ResourceManager.GetString("LastPackedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        public static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string LightThemeTitle {
            get {
                return ResourceManager.GetString("LightThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        public static string Listening {
            get {
                return ResourceManager.GetString("Listening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading activities....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading packing….
        /// </summary>
        public static string LoadingPacking {
            get {
                return ResourceManager.GetString("LoadingPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading payment options....
        /// </summary>
        public static string LoadingProducts {
            get {
                return ResourceManager.GetString("LoadingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone permission denied.
        /// </summary>
        public static string MicrophonePermissionDenied {
            get {
                return ResourceManager.GetString("MicrophonePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please allow microphone access in your browser settings to use voice dictation.
        /// </summary>
        public static string MicrophonePermissionHelp {
            get {
                return ResourceManager.GetString("MicrophonePermissionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~{0} min remaining.
        /// </summary>
        public static string MinRemaining {
            get {
                return ResourceManager.GetString("MinRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months ago.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string Multiple {
            get {
                return ResourceManager.GetString("Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation menu.
        /// </summary>
        public static string NavigationMenu {
            get {
                return ResourceManager.GetString("NavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error. Please check your internet connection..
        /// </summary>
        public static string NetworkErrorSpeech {
            get {
                return ResourceManager.GetString("NetworkErrorSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Packing Activity.
        /// </summary>
        public static string NewPackingActivity {
            get {
                return ResourceManager.GetString("NewPackingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Packing Activities.
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first packing activity to get started..
        /// </summary>
        public static string NoActivitiesDescription {
            get {
                return ResourceManager.GetString("NoActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items yet.
        /// </summary>
        public static string NoItemsYet {
            get {
                return ResourceManager.GetString("NoItemsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages yet.
        /// </summary>
        public static string NoMessagesYet {
            get {
                return ResourceManager.GetString("NoMessagesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No previous purchases found..
        /// </summary>
        public static string NoPurchasesToRestore {
            get {
                return ResourceManager.GetString("NoPurchasesToRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No speech detected. Please try speaking again..
        /// </summary>
        public static string NoSpeechDetected {
            get {
                return ResourceManager.GetString("NoSpeechDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get notified about important updates.
        /// </summary>
        public static string NotifiedAboutUpdates {
            get {
                return ResourceManager.GetString("NotifiedAboutUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline mode: your changes are saved locally..
        /// </summary>
        public static string OfflineChangesSaved {
            get {
                return ResourceManager.GetString("OfflineChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time.
        /// </summary>
        public static string OneTimeActivity {
            get {
                return ResourceManager.GetString("OneTimeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archives automatically after completion.
        /// </summary>
        public static string OneTimeActivityDescription {
            get {
                return ResourceManager.GetString("OneTimeActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        public static string OpenSettings {
            get {
                return ResourceManager.GetString("OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OtherPayment {
            get {
                return ResourceManager.GetString("OtherPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Ways to Reach Us.
        /// </summary>
        public static string OtherWaysToReach {
            get {
                return ResourceManager.GetString("OtherWaysToReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packed {0} items in {1} minutes.
        /// </summary>
        public static string PackedItemsInMinutes {
            get {
                return ResourceManager.GetString("PackedItemsInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Activities.
        /// </summary>
        public static string PackingActivitiesMenu {
            get {
                return ResourceManager.GetString("PackingActivitiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Activity.
        /// </summary>
        public static string PackingActivity {
            get {
                return ResourceManager.GetString("PackingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing activity copied successfully..
        /// </summary>
        public static string PackingActivityCopied {
            get {
                return ResourceManager.GetString("PackingActivityCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Complete!.
        /// </summary>
        public static string PackingComplete {
            get {
                return ResourceManager.GetString("PackingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Dialog.
        /// </summary>
        public static string PackingDialogMenu {
            get {
                return ResourceManager.GetString("PackingDialogMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing History.
        /// </summary>
        public static string PackingHistory {
            get {
                return ResourceManager.GetString("PackingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Now.
        /// </summary>
        public static string PackNow {
            get {
                return ResourceManager.GetString("PackNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via PayPal.
        /// </summary>
        public static string PayPalHint {
            get {
                return ResourceManager.GetString("PayPalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to PayPal. Complete the payment in your browser..
        /// </summary>
        public static string PayPalRedirect {
            get {
                return ResourceManager.GetString("PayPalRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your messages are encrypted and private.
        /// </summary>
        public static string PrivacyNotice {
            get {
                return ResourceManager.GetString("PrivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing....
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your purchases have been restored..
        /// </summary>
        public static string PurchasesRestored {
            get {
                return ResourceManager.GetString("PurchasesRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications.
        /// </summary>
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring.
        /// </summary>
        public static string RecurringActivity {
            get {
                return ResourceManager.GetString("RecurringActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets after each use (e.g., business trips).
        /// </summary>
        public static string RecurringActivityDescription {
            get {
                return ResourceManager.GetString("RecurringActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unfinished packing activities..
        /// </summary>
        public static string ReminderNotificationBodyMultiple {
            get {
                return ResourceManager.GetString("ReminderNotificationBodyMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to finish packing &quot;{0}&quot;!.
        /// </summary>
        public static string ReminderNotificationBodySingle {
            get {
                return ResourceManager.GetString("ReminderNotificationBodySingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Reminder.
        /// </summary>
        public static string ReminderNotificationTitle {
            get {
                return ResourceManager.GetString("ReminderNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Items.
        /// </summary>
        public static string ResetAllItems {
            get {
                return ResourceManager.GetString("ResetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Packing List.
        /// </summary>
        public static string ResetPackingList {
            get {
                return ResourceManager.GetString("ResetPackingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not restore purchases. Please try again..
        /// </summary>
        public static string RestoreFailed {
            get {
                return ResourceManager.GetString("RestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore previous purchases.
        /// </summary>
        public static string RestorePurchases {
            get {
                return ResourceManager.GetString("RestorePurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll to top.
        /// </summary>
        public static string ScrollToTop {
            get {
                return ResourceManager.GetString("ScrollToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search activities....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure payment powered by your device.
        /// </summary>
        public static string SecurePayment {
            get {
                return ResourceManager.GetString("SecurePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an amount.
        /// </summary>
        public static string SelectAmount {
            get {
                return ResourceManager.GetString("SelectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category:.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to send.
        /// </summary>
        public static string SendFailed {
            get {
                return ResourceManager.GetString("SendFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send your first message to get help from our support team.
        /// </summary>
        public static string SendFirstMessage {
            get {
                return ResourceManager.GetString("SendFirstMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending....
        /// </summary>
        public static string Sending {
            get {
                return ResourceManager.GetString("Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session progress has been saved..
        /// </summary>
        public static string SessionSavedMessage {
            get {
                return ResourceManager.GetString("SessionSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Activity.
        /// </summary>
        public static string SharedActivity {
            get {
                return ResourceManager.GetString("SharedActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Items.
        /// </summary>
        public static string ShowAllItems {
            get {
                return ResourceManager.GetString("ShowAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition error: {0}.
        /// </summary>
        public static string SpeechError {
            get {
                return ResourceManager.GetString("SpeechError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition is not supported in your browser.
        /// </summary>
        public static string SpeechNotSupported {
            get {
                return ResourceManager.GetString("SpeechNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Dictation.
        /// </summary>
        public static string StartDictation {
            get {
                return ResourceManager.GetString("StartDictation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start first packing.
        /// </summary>
        public static string StartFirstTrip {
            get {
                return ResourceManager.GetString("StartFirstTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Packing.
        /// </summary>
        public static string StartPacking {
            get {
                return ResourceManager.GetString("StartPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Highlights.
        /// </summary>
        public static string StatsActivityBreakdown {
            get {
                return ResourceManager.GetString("StatsActivityBreakdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average packing time.
        /// </summary>
        public static string StatsAvgTime {
            get {
                return ResourceManager.GetString("StatsAvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Insights.
        /// </summary>
        public static string StatsCategoryInsights {
            get {
                return ResourceManager.GetString("StatsCategoryInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string StatsEfficiency {
            get {
                return ResourceManager.GetString("StatsEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete some packing sessions to see detailed time stats, activity breakdowns, and usage patterns here..
        /// </summary>
        public static string StatsEmptyHint {
            get {
                return ResourceManager.GetString("StatsEmptyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest session.
        /// </summary>
        public static string StatsFastestSession {
            get {
                return ResourceManager.GetString("StatsFastestSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items.
        /// </summary>
        public static string StatsItemCountValue {
            get {
                return ResourceManager.GetString("StatsItemCountValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Packed.
        /// </summary>
        public static string StatsItemsPacked {
            get {
                return ResourceManager.GetString("StatsItemsPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string StatsLastMonth {
            get {
                return ResourceManager.GetString("StatsLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatsMenu {
            get {
                return ResourceManager.GetString("StatsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Active Day.
        /// </summary>
        public static string StatsMostActiveDay {
            get {
                return ResourceManager.GetString("StatsMostActiveDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Efficient.
        /// </summary>
        public static string StatsMostEfficient {
            get {
                return ResourceManager.GetString("StatsMostEfficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largest List.
        /// </summary>
        public static string StatsMostItems {
            get {
                return ResourceManager.GetString("StatsMostItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Packed.
        /// </summary>
        public static string StatsMostPacked {
            get {
                return ResourceManager.GetString("StatsMostPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Improvement.
        /// </summary>
        public static string StatsNeedsWork {
            get {
                return ResourceManager.GetString("StatsNeedsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string StatsOverview {
            get {
                return ResourceManager.GetString("StatsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Sessions.
        /// </summary>
        public static string StatsRecentTrend {
            get {
                return ResourceManager.GetString("StatsRecentTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sessions.
        /// </summary>
        public static string StatsSessionCount {
            get {
                return ResourceManager.GetString("StatsSessionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Streak.
        /// </summary>
        public static string StatsStreak {
            get {
                return ResourceManager.GetString("StatsStreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string StatsThisMonth {
            get {
                return ResourceManager.GetString("StatsThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Stats.
        /// </summary>
        public static string StatsTimeTitle {
            get {
                return ResourceManager.GetString("StatsTimeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top category: {0}.
        /// </summary>
        public static string StatsTopCategory {
            get {
                return ResourceManager.GetString("StatsTopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string StatsTotalActivities {
            get {
                return ResourceManager.GetString("StatsTotalActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string StatsTotalSessions {
            get {
                return ResourceManager.GetString("StatsTotalSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time packing.
        /// </summary>
        public static string StatsTotalTime {
            get {
                return ResourceManager.GetString("StatsTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Patterns.
        /// </summary>
        public static string StatsUsagePatterns {
            get {
                return ResourceManager.GetString("StatsUsagePatterns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Dictation.
        /// </summary>
        public static string StopDictation {
            get {
                return ResourceManager.GetString("StopDictation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage permission is required to save and load your packing data. You can enable it later in system settings..
        /// </summary>
        public static string StoragePermissionRequiredMessage {
            get {
                return ResourceManager.GetString("StoragePermissionRequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Required.
        /// </summary>
        public static string StoragePermissionRequiredTitle {
            get {
                return ResourceManager.GetString("StoragePermissionRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure store payment.
        /// </summary>
        public static string StorePaymentHint {
            get {
                return ResourceManager.GetString("StorePaymentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportMenu {
            get {
                return ResourceManager.GetString("SupportMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Team.
        /// </summary>
        public static string SupportTeam {
            get {
                return ResourceManager.GetString("SupportTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve Anticipack.
        /// </summary>
        public static string SupportUsDescription {
            get {
                return ResourceManager.GetString("SupportUsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Packed.
        /// </summary>
        public static string TimesPacked {
            get {
                return ResourceManager.GetString("TimesPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message....
        /// </summary>
        public static string TypeYourMessage {
            get {
                return ResourceManager.GetString("TypeYourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unarchive.
        /// </summary>
        public static string Unarchive {
            get {
                return ResourceManager.GetString("Unarchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnamed Item.
        /// </summary>
        public static string UnnamedItem {
            get {
                return ResourceManager.GetString("UnnamedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} weeks ago.
        /// </summary>
        public static string WeeksAgo {
            get {
                return ResourceManager.GetString("WeeksAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first activity to start packing faster and stay organized..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Anticipack.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Anticipack Support! How can we help you today?.
        /// </summary>
        public static string WelcomeToSupport {
            get {
                return ResourceManager.GetString("WelcomeToSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You packed {0} items in {1}.
        /// </summary>
        public static string YouPackedItems {
            get {
                return ResourceManager.GetString("YouPackedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Messages.
        /// </summary>
        public static string YourMessages {
            get {
                return ResourceManager.GetString("YourMessages", resourceCulture);
            }
        }
    }
}
