//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anticipack.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Anticipack.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity created successfully.
        /// </summary>
        public static string ActivityCreated {
            get {
                return ResourceManager.GetString("ActivityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity deleted successfully.
        /// </summary>
        public static string ActivityDeleted {
            get {
                return ResourceManager.GetString("ActivityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        public static string AutoTheme {
            get {
                return ResourceManager.GetString("AutoTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app will automatically match your device&apos;s system theme.
        /// </summary>
        public static string AutoThemeHint {
            get {
                return ResourceManager.GetString("AutoThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic theme based on system preferences.
        /// </summary>
        public static string AutoThemeTitle {
            get {
                return ResourceManager.GetString("AutoThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Time.
        /// </summary>
        public static string AvgTime {
            get {
                return ResourceManager.GetString("AvgTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessories.
        /// </summary>
        public static string Category_Accessories {
            get {
                return ResourceManager.GetString("Category_Accessories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        public static string Category_Clothing {
            get {
                return ResourceManager.GetString("Category_Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Category_Documents {
            get {
                return ResourceManager.GetString("Category_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        public static string Category_Electronics {
            get {
                return ResourceManager.GetString("Category_Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Category_Entertainment {
            get {
                return ResourceManager.GetString("Category_Entertainment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Category_Food {
            get {
                return ResourceManager.GetString("Category_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string Category_Health {
            get {
                return ResourceManager.GetString("Category_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Category_Miscellaneous {
            get {
                return ResourceManager.GetString("Category_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outdoor.
        /// </summary>
        public static string Category_Outdoor {
            get {
                return ResourceManager.GetString("Category_Outdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        public static string Category_Shoes {
            get {
                return ResourceManager.GetString("Category_Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toiletries.
        /// </summary>
        public static string Category_Toiletries {
            get {
                return ResourceManager.GetString("Category_Toiletries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language.
        /// </summary>
        public static string ChoosePreferredLanguage {
            get {
                return ResourceManager.GetString("ChoosePreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string ClearCache {
            get {
                return ResourceManager.GetString("ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compared to Last Time.
        /// </summary>
        public static string ComparedToLastTime {
            get {
                return ResourceManager.GetString("ComparedToLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to mark all items as unpacked?.
        /// </summary>
        public static string ConfirmResetAllItems {
            get {
                return ResourceManager.GetString("ConfirmResetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to Edit.
        /// </summary>
        public static string ContinueToEdit {
            get {
                return ResourceManager.GetString("ContinueToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Packing Activity.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize your experience.
        /// </summary>
        public static string CustomizeExperience {
            get {
                return ResourceManager.GetString("CustomizeExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme reduces eye strain in low-light environments.
        /// </summary>
        public static string DarkThemeHint {
            get {
                return ResourceManager.GetString("DarkThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        public static string DarkThemeTitle {
            get {
                return ResourceManager.GetString("DarkThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data &amp; Storage.
        /// </summary>
        public static string DataStorage {
            get {
                return ResourceManager.GetString("DataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &quot;{0}&quot;? This action cannot be undone..
        /// </summary>
        public static string DeleteActivityMessage {
            get {
                return ResourceManager.GetString("DeleteActivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Activity?.
        /// </summary>
        public static string DeleteActivityTitle {
            get {
                return ResourceManager.GetString("DeleteActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Activity.
        /// </summary>
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing this packing list might affect your current packing progress..
        /// </summary>
        public static string EditingMightAffectProgress {
            get {
                return ResourceManager.GetString("EditingMightAffectProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting items: {0}.
        /// </summary>
        public static string ErrorResettingItems {
            get {
                return ResourceManager.GetString("ErrorResettingItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving item state: {0}.
        /// </summary>
        public static string ErrorSavingItemState {
            get {
                return ResourceManager.GetString("ErrorSavingItemState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create activity.
        /// </summary>
        public static string FailedToCreate {
            get {
                return ResourceManager.GetString("FailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete activity.
        /// </summary>
        public static string FailedToDelete {
            get {
                return ResourceManager.GetString("FailedToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load activities.
        /// </summary>
        public static string FailedToLoad {
            get {
                return ResourceManager.GetString("FailedToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load items.
        /// </summary>
        public static string FailedToLoadItems {
            get {
                return ResourceManager.GetString("FailedToLoadItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free up storage space.
        /// </summary>
        public static string FreeUpStorage {
            get {
                return ResourceManager.GetString("FreeUpStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great!.
        /// </summary>
        public static string Great {
            get {
                return ResourceManager.GetString("Great", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Checked Items.
        /// </summary>
        public static string HideCheckedItems {
            get {
                return ResourceManager.GetString("HideCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide History.
        /// </summary>
        public static string HideHistory {
            get {
                return ResourceManager.GetString("HideHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string HideLabel {
            get {
                return ResourceManager.GetString("HideLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ {0} packed.
        /// </summary>
        public static string ItemPacked {
            get {
                return ResourceManager.GetString("ItemPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}/{1} items packed.
        /// </summary>
        public static string ItemsPacked {
            get {
                return ResourceManager.GetString("ItemsPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ◯ {0} unpacked.
        /// </summary>
        public static string ItemUnpacked {
            get {
                return ResourceManager.GetString("ItemUnpacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last packed:.
        /// </summary>
        public static string LastPacked {
            get {
                return ResourceManager.GetString("LastPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Packed.
        /// </summary>
        public static string LastPackedLabel {
            get {
                return ResourceManager.GetString("LastPackedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme is ideal for bright environments.
        /// </summary>
        public static string LightThemeHint {
            get {
                return ResourceManager.GetString("LightThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        public static string LightThemeTitle {
            get {
                return ResourceManager.GetString("LightThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading activities....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading packing….
        /// </summary>
        public static string LoadingPacking {
            get {
                return ResourceManager.GetString("LoadingPacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your app data.
        /// </summary>
        public static string ManageAppData {
            get {
                return ResourceManager.GetString("ManageAppData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your notification preferences.
        /// </summary>
        public static string ManageNotificationPreferences {
            get {
                return ResourceManager.GetString("ManageNotificationPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~{0} min remaining.
        /// </summary>
        public static string MinRemaining {
            get {
                return ResourceManager.GetString("MinRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Packing Activity.
        /// </summary>
        public static string NewPackingActivity {
            get {
                return ResourceManager.GetString("NewPackingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Packing Activities.
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your first packing activity to get started..
        /// </summary>
        public static string NoActivitiesDescription {
            get {
                return ResourceManager.GetString("NoActivitiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get notified about important updates.
        /// </summary>
        public static string NotifiedAboutUpdates {
            get {
                return ResourceManager.GetString("NotifiedAboutUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Activity.
        /// </summary>
        public static string PackingActivity {
            get {
                return ResourceManager.GetString("PackingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Complete!.
        /// </summary>
        public static string PackingComplete {
            get {
                return ResourceManager.GetString("PackingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing completed and recorded!.
        /// </summary>
        public static string PackingCompletedRecorded {
            get {
                return ResourceManager.GetString("PackingCompletedRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing History.
        /// </summary>
        public static string PackingHistory {
            get {
                return ResourceManager.GetString("PackingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pack Now.
        /// </summary>
        public static string PackNow {
            get {
                return ResourceManager.GetString("PackNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalize how the app looks and feels.
        /// </summary>
        public static string PersonalizeAppLooks {
            get {
                return ResourceManager.GetString("PersonalizeAppLooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Notifications.
        /// </summary>
        public static string PushNotifications {
            get {
                return ResourceManager.GetString("PushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        public static string ResetAll {
            get {
                return ResourceManager.GetString("ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All Items.
        /// </summary>
        public static string ResetAllItems {
            get {
                return ResourceManager.GetString("ResetAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset {0} items.
        /// </summary>
        public static string ResetItemsSuccess {
            get {
                return ResourceManager.GetString("ResetItemsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Packing List.
        /// </summary>
        public static string ResetPackingList {
            get {
                return ResourceManager.GetString("ResetPackingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search activities....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Items.
        /// </summary>
        public static string ShowAllItems {
            get {
                return ResourceManager.GetString("ShowAllItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string ShowCheckedItems {
            get {
                return ResourceManager.GetString("ShowCheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show History.
        /// </summary>
        public static string ShowHistory {
            get {
                return ResourceManager.GetString("ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Edit Mode?.
        /// </summary>
        public static string SwitchToEditMode {
            get {
                return ResourceManager.GetString("SwitchToEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times Packed.
        /// </summary>
        public static string TimesPacked {
            get {
                return ResourceManager.GetString("TimesPacked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You packed {0} items in {1}.
        /// </summary>
        public static string YouPackedItems {
            get {
                return ResourceManager.GetString("YouPackedItems", resourceCulture);
            }
        }
    }
}
